# Generated by Django 3.2.16 on 2022-11-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='last_update',
            field=models.DateTimeField(verbose_name='Последнее обновление'),
        ),
    ]
