# Generated by Django 3.2.16 on 2022-11-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmaps', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparam',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.site', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.block', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='block',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.roadmap', verbose_name='Родитель'),
        ),
        migrations.AlterUniqueTogether(
            name='siteparam',
            unique_together={('block', 'site')},
        ),
    ]
