# Generated by Django 3.2.16 on 2022-11-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_response_last_update'),
        ('roadmaps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.roadmap', verbose_name='Дорожная карта'),
        ),
        migrations.AlterField(
            model_name='siteparam',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.site', verbose_name='Сайт'),
        ),
    ]
